# Generated by Django 4.2.6 on 2023-12-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_leaderboard_rank_leaderboard_total_cf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
