# Generated by Django 4.2.6 on 2023-12-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_userinput_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoprofile',
            name='sustainability_score',
        ),
        migrations.AlterField(
            model_name='ecoprofile',
            name='carbon_footprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.leaderboard'),
        ),
        migrations.DeleteModel(
            name='CarbonFootprint',
        ),
    ]
