# Generated by Django 4.2.6 on 2023-12-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_ecoprofile_sustainability_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcoProfile',
        ),
    ]
