# Generated by Django 4.2.6 on 2023-12-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_ecoprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
