# Generated by Django 4.2.6 on 2023-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_leaderboard_latest_cf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilitychallenge',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sustainabilitychallenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sustainabilitychallenge',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='sustainabilitychallenge',
            name='start_date',
        ),
    ]
