# Generated by Django 4.2.6 on 2023-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
