# Generated by Django 4.2.6 on 2023-12-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_userchallenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilitychallenge',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustainabilitychallenge',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sustainabilitychallenge',
            name='participants',
            field=models.ManyToManyField(related_name='joined_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustainabilitychallenge',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
