# Generated by Django 4.2.6 on 2023-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_sustainabilitychallenge_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='title',
        ),
        migrations.AddField(
            model_name='reward',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sustainabilitychallenge',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
