# Generated by Django 4.2.6 on 2023-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_reward_description_remove_reward_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
